@startuml

hide footbox
skinparam monochrome true
skinparam shadowing false

activate JQueryDatepicker


JQueryDatepicker -> JQueryDatepicker : displayMonth()

group private int displayMonth()

JQueryDatepicker -> Browser: await(CALENDAR)
activate Browser

Browser -> Element: <<create>>
activate Element
Element --> Browser
deactivate Element

Browser -> JQueryDatepicker: Element
deactivate Browser

JQueryDatepicker -> Element : getText(MONTH)
activate Element
Element -> JQueryDatepicker : displayMonth
deactivate Element

deactivate JQueryDatepicker
end

@enduml
