@startuml

hide footbox
skinparam monochrome true
skinparam shadowing false

activate JQueryDatepicker

JQueryDatepicker -> JQueryDatepicker : nextMonth()

group private void nextMonth()

JQueryDatepicker -> Browser : await(CALENDAR)

activate Browser
Browser -> Element: <<create>>
activate Element
Element --> Browser
deactivate Element

Browser -> JQueryDatepicker : Element

deactivate Browser
JQueryDatepicker -> Element: click(NEXT_MONTH_BUTTON)
activate Element
Element --> JQueryDatepicker :
deactivate Element
deactivate JQueryDatepicker

end

@enduml
